# Generated by Django 3.2.7 on 2021-09-23 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_referermodel_referer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Referer',
            new_name='Refererrr',
        ),
    ]
