# Generated by Django 3.2.7 on 2021-09-23 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_referer_refererrr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, verbose_name='firstname')),
                ('middlename', models.CharField(max_length=30, verbose_name='middleware')),
                ('lastname', models.CharField(max_length=30, verbose_name='lastname')),
                ('cnic', models.CharField(max_length=30, verbose_name='cnic')),
                ('designation', models.CharField(max_length=30, verbose_name='designation')),
                ('address', models.CharField(max_length=30, verbose_name='address')),
                ('snap', models.TextField(blank=True, verbose_name='snap')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date.created')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date.updated')),
            ],
            options={
                'db_table': 'referer',
            },
        ),
        migrations.DeleteModel(
            name='Refererrr',
        ),
    ]
