# Generated by Django 3.2.7 on 2021-09-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_referer_snap'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='referer',
            table='refererr',
        ),
    ]
