# Generated by Django 3.2.7 on 2021-09-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_referer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='referer',
            table='referer',
        ),
    ]
